# Generated by Django 5.1.4 on 2024-12-08 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_profile_profile_picture_alter_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Profile_picture',
            new_name='profile_picture',
        ),
    ]
