# Generated by Django 5.1.3 on 2024-11-15 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_add_book', 'can create a book instance.'), ('can_change_book', 'can edit a book instance'), ('can_delete_book', 'can delete a book instance'))},
        ),
    ]
